services:
  - type: worker
    name: onboarding-websocket
    runtime: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
